spring.application.name=delivery-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lastmile_delivery}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.debug=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
curl -i -X POST "http://localhost:8080/api/reschedules/1?newDeliveryDate=2026-08-25&reason=Customer%20requested%20reschedule&actorId=4" \
-H "Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjdXN0b21lckB0ZXN0LmNvbSIsImlhdCI6MTc4NzUwNTEzOSwiZXhwIjoxNzg3NTkxNTM5fQ.u86JYXkOfXSOIu2yxT-Lf9TXmKynIIf2p_GuMRrt_wr4J6zIBq29MWM9YoC5x-18"
jwt.secret=${JWT_SECRET:your-super-secret-key-that-is-at-least-32-characters-long}
server.port=8080